### ISSUE TITLE
Deleting tags is a problem

### ISSUE THREAD

**Issue by gobfink** [gobfink/AcronymDB#1]
When you delete a tag its still listed when editing an acronym. Also if it was tagged and then deleted it will still think its tag when editing, but correctly won't show up on the menu

**Comment by kgustafson** [comment]
Related.  Editing a tag will end up showing BOTH the old name and the new name in the pick list for Tags during an acronym edit.  Weird stuff!

**Comment by gobfink** [comment]
I think its due to the way we are parsing the acrotag db. Like maybe it
gets a new entry when we edit it? I think we probably just need to do some
cleanup on that end

**Comment by kgustafson** [comment]
This has been fixed with the latest push to tag_bug.  We need to roll this tag_bug branch into master.
