### ISSUE TITLE
Code base on persisted local volume

### ISSUE THREAD

**Issue by kgustafson** [gobfink/AcronymDB#2]
Need to make the flask code base editable via a local link.  This will allow changes to the code base without a restart of the docker containers.  Will require setting the local volume in docker-compose.yml file.  Will require moving the flask/code/app code base to the local directory (recommend calling it /code/app under AcronymDB.)

**Comment by kgustafson** [comment]
Not sure we can do this in the way that flask operates.  Will require more research.

**Comment by gobfink** [comment]
I haven't been able to find anything conclusive either. I know that flask
mounts a volume, and when i attach to it i can see changes - however i
think it needs to rebuild itself

**Comment by gobfink** [comment]
Fixed this. We had a nasty bug - basically we mount the code as a volume but also copied and ran a version of the code in with the dockerfile. I updated the dockerfile to point to the volume we mounted
